image: gitpod/workspace-base

tasks:
- name: install mamba
  init: |
    cd /workspace
    wget "https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Mambaforge-24.3.0-0-Linux-x86_64.sh"
    bash Mambaforge-24.3.0-0-Linux-x86_64.sh -b -p /workspace/mambaforge && rm Mambaforge-24.3.0-0-Linux-x86_64.sh

    /workspace/mambaforge/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba create -n kmers -c conda-forge r-base r-argparse r-viridis r-minpack.lm -y
    mamba activate kmers
    mamba install -c bioconda sourmash -y
    
    pip3 install numpy pandas sourmash_plugin_betterplot
    sudo apt install -y libgl1

    cd /workspace
    mkdir src bin && cd src # create directories for source code & binaries
    git clone -b sploidyplot_obj https://github.com/KamilSJaron/smudgeplot
    git clone https://github.com/thegenemyers/FastK
    git clone https://github.com/thegenemyers/MERQURY.FK
    git clone --depth 1 https://github.com/tbenavi1/genomescope2.0
    git clone https://github.com/KamilSJaron/GenomeTelescope

    cd smudgeplot
    python -m pip install .
    mkdir -p exec && make exec/hetmers exec/extract_kmer_pairs
    install -c exec/hetmers exec/extract_kmer_pairs /workspace/bin/

    # install FastK
    cd /workspace/src/FastK && make
    install -c FastK Fastrm Fastmv Fastcp Fastmerge Histex Tabex Profex Logex Vennex Symmex Haplex Homex Fastcat /workspace/bin/

    # install MERQURY.FK
    cd /workspace/src/MERQURY.FK && make
    install -c HAPmaker CNplot ASMplot HAPplot MerquryFK KatComp KatGC /workspace/bin/

    # install genomescope2 (both package and executible script)
    cd /workspace/src/
    R -e 'install.packages("genomescope2.0", repos=NULL, type="source")'
    install -c genomescope2.0/genomescope.R /workspace/bin

    # install genomeTelescope R package 
    R -e 'install.packages("GenomeTelescope", repos=NULL, type="source")'
    
    cd /workspace
    git clone --depth 1 https://github.com/WCSCourses/K-mer_Biodiversity_Genomics_2025.git
    ln -s /workspace/K-mer_Biodiversity_Genomics_2025/course_data_2025 .
    
    mkdir -p data/Scer && wget -P data/Scer https://sk13.cog.sanger.ac.uk/SRR3265401_{1,2}.fastq.gz
    
    gp sync-done bundle
    
- name: activate mamba
  init: gp sync-await bundle # Wait for previous 'inits' to complete
  command: |
    cd /workspace
    /workspace/mambaforge/bin/mamba init bash
    source ~/.bashrc 
    mamba activate kmers
    
    export PATH=/workspace/bin:"$PATH"

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"
